# Generated by Django 5.2.7 on 2025-10-13 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.directorate')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.division')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('GL_01', 'GL 01'), ('GL_02', 'GL 02'), ('GL_03', 'GL 03'), ('GL_04', 'GL 04'), ('GL_05', 'GL 05'), ('GL_06', 'GL 06'), ('GL_07', 'GL 07'), ('GL_08', 'GL 08'), ('GL_09', 'GL 09'), ('GL_10', 'GL 10'), ('GL_11', 'GL 11'), ('GL_12', 'GL 12'), ('GL_13', 'GL 13'), ('GL_14', 'GL 14'), ('GL_15', 'GL 15'), ('GL_16', 'GL 16'), ('GL_17', 'GL 17')], max_length=10)),
                ('date_joined', models.DateField()),
                ('training_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.department')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.directorate')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.division')),
            ],
        ),
        migrations.CreateModel(
            name='NominationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nominations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_staff', models.ManyToManyField(through='training.NominationItem', to='training.staff')),
            ],
        ),
        migrations.AddField(
            model_name='nominationitem',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingnomination'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainingnomination',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingprogram'),
        ),
        migrations.CreateModel(
            name='TrainingSelectionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_levels', models.JSONField()),
                ('max_previous_trainings', models.IntegerField(default=5)),
                ('min_years_of_service', models.IntegerField(default=0)),
                ('max_years_of_service', models.IntegerField(default=50)),
                ('departments', models.ManyToManyField(to='training.department')),
                ('directorates', models.ManyToManyField(to='training.directorate')),
                ('divisions', models.ManyToManyField(to='training.division')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='training.trainingprogram')),
            ],
        ),
        migrations.AddField(
            model_name='trainingnomination',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingselectioncriteria'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('training_staff', 'Training Staff'), ('admin', 'Administrator')], max_length=20)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.directorate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nominationitem',
            unique_together={('nomination', 'staff')},
        ),
    ]
