# Generated by Django 5.2.7 on 2025-10-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade_level',
            field=models.CharField(choices=[('GL_04', 'GL 04'), ('GL_06', 'GL 06'), ('GL_07', 'GL 07'), ('GL_08', 'GL 08'), ('GL_09', 'GL 09'), ('GL_10', 'GL 10'), ('GL_12', 'GL 12'), ('GL_13', 'GL 13'), ('GL_14', 'GL 14'), ('GL_15', 'GL 15'), ('GL_16', 'GL 16')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingselectioncriteria',
            name='max_previous_trainings',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='trainingselectioncriteria',
            name='max_years_of_service',
            field=models.IntegerField(default=35),
        ),
    ]
