# Generated by Django 5.2.7 on 2025-10-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_staff_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(choices=[('ALL', 'All'), ('LPC', 'LPC'), ('TCIPC', 'TCIPC'), ('RP', 'RP'), ('CAL', 'CAL'), ('HQ', 'HQ'), ('DP', 'DP'), ('ONNE', 'ONNE'), ('ABJ', 'ABJ')], default='HQ', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingselectioncriteria',
            name='locations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.department'),
        ),
    ]
