# Generated by Django 5.2.7 on 2025-10-14 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_nominalrollupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingselectioncriteria',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingselectioncriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingselectioncriteria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainingselectioncriteria',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingprogram'),
        ),
    ]
