# Generated by Django 5.2.7 on 2025-10-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingselectioncriteria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('training_staff', 'Training Staff'), ('admin', 'Administrator'), ('admin_officer', 'Admin Officer')], max_length=20),
        ),
    ]
