# Generated by Django 5.2.7 on 2025-10-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_trainingnomination_print_hash_and_more'),
    ]

    operations = [
    ]
