# Generated by Django 5.2.7 on 2025-10-14 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_update_existing_trainings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='description',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='consultant_info',
            field=models.TextField(blank=True, help_text='Consultant qualifications and experience', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or special instructions'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_consultant',
            field=models.CharField(blank=True, help_text='Name of training consultant/facilitator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'training_staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='capacity',
            field=models.IntegerField(default=25),
        ),
    ]
